# Generated by Django 2.1.5 on 2019-03-01 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('carr_id', models.AutoField(primary_key=True, serialize=False)),
                ('carr_codi', models.CharField(max_length=3)),
                ('carr_nomb', models.CharField(max_length=30)),
                ('carr_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nomb', models.CharField(max_length=60)),
                ('cli_ape1', models.CharField(max_length=30)),
                ('cli_ape2', models.CharField(blank=True, max_length=30, null=True)),
                ('cli_acti', models.BooleanField(default=True)),
                ('carr_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.Carrera')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nomb', models.CharField(max_length=60)),
                ('emp_ape1', models.CharField(max_length=30)),
                ('emp_ape2', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_cedu', models.CharField(blank=True, max_length=11, null=True)),
                ('emp_entra', models.DateField()),
                ('emp_sale', models.DateField(blank=True, null=True)),
                ('emp_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('fpago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpago_nomb', models.CharField(max_length=30)),
                ('fpago_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'forma_pago',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('hor_id', models.AutoField(primary_key=True, serialize=False)),
                ('hor_nomb', models.CharField(max_length=30)),
                ('hor_entra', models.TimeField()),
                ('hor_sale', models.TimeField()),
                ('hor_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='ModoPago',
            fields=[
                ('mpago_id', models.AutoField(primary_key=True, serialize=False)),
                ('mpago_nomb', models.CharField(max_length=30)),
                ('mpago_cuot', models.IntegerField()),
                ('mpago_inte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mpago_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modo_pago',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('mov_fecha', models.DateTimeField(auto_now_add=True)),
                ('mov_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mov_acti', models.BooleanField(default=True)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.Cliente')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.Empleado')),
                ('fpago_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.FormaPago')),
                ('mpago_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.ModoPago')),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nomb', models.CharField(max_length=30)),
                ('prod_prec', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prod_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tcli_id', models.AutoField(primary_key=True, serialize=False)),
                ('tcli_nomb', models.CharField(max_length=30)),
                ('tcli_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tdoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('tdoc_nomb', models.CharField(max_length=30)),
                ('tdoc_acti', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.Producto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tdoc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.TipoDocumento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.Horario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tcli_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Caja.TipoCliente'),
        ),
    ]
